"""empty message

Revision ID: ca5a2cf24a00
Revises: 
Create Date: 2025-12-05 03:36:55.584679+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5a2cf24a00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_item',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('skill_area', sa.JSON(), nullable=False),
    sa.Column('target_proficiency_level', sa.String(length=15), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_item'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=True),
    sa.Column('actor_type', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.CHAR(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_table('learning_pathway',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_pathway')),
    sa.UniqueConstraint('name', name=op.f('uq_learning_pathway_name'))
    )
    op.create_table('assessment_template',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('learning_pathway_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('assessment_type', sa.Enum('PLACEMENT', 'SPEAKING', 'WRITING', name='assessmenttype'), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learning_pathway_id'], ['learning_pathway.id'], name=op.f('fk_assessment_template_learning_pathway_id_learning_pathway')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_template'))
    )
    op.create_table('course',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('pathway_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('target_proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('primary_skill', sa.String(length=50), nullable=True),
    sa.Column('secondary_skills', sa.JSON(), nullable=True),
    sa.Column('skill_scores', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_hours', sa.DECIMAL(), nullable=True),
    sa.Column('difficulty_order', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pathway_id'], ['learning_pathway.id'], name=op.f('fk_course_pathway_id_learning_pathway')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course'))
    )
    op.create_table('assessment_config',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('template_id', sa.CHAR(length=36), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('adaptive_params', sa.JSON(), nullable=True),
    sa.Column('speaking_params', sa.JSON(), nullable=True),
    sa.Column('writing_params', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_template.id'], name=op.f('fk_assessment_config_template_id_assessment_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_config'))
    )
    op.create_table('assigned_assessment',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('template_id', sa.CHAR(length=36), nullable=False),
    sa.Column('test_taker_id', sa.String(length=50), nullable=False),
    sa.Column('test_taker_type', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='testtakertype'), nullable=False),
    sa.Column('assigned_by', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='assignmentstatus'), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_template.id'], name=op.f('fk_assigned_assessment_template_id_assessment_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assigned_assessment'))
    )
    op.create_index(op.f('ix_assigned_assessment_status'), 'assigned_assessment', ['status'], unique=False)
    op.create_index(op.f('ix_assigned_assessment_test_taker_id'), 'assigned_assessment', ['test_taker_id'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('course_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('lesson_order', sa.Integer(), nullable=True),
    sa.Column('target_skills', sa.JSON(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('relative_difficulty', sa.DECIMAL(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.DECIMAL(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_lesson_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson'))
    )
    op.create_table('template_item',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('template_id', sa.CHAR(length=36), nullable=False),
    sa.Column('item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=True),
    sa.Column('item_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_item.id'], name=op.f('fk_template_item_item_id_assessment_item')),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_template.id'], name=op.f('fk_template_item_template_id_assessment_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_item'))
    )
    op.create_table('assessment_session',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('assigned_id', sa.CHAR(length=36), nullable=False),
    sa.Column('current_ability', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('standard_error', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='sessionstatus'), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=True),
    sa.Column('rubric_snapshot', sa.JSON(), nullable=True),
    sa.Column('template_snapshot', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_id'], ['assigned_assessment.id'], name=op.f('fk_assessment_session_assigned_id_assigned_assessment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_session'))
    )
    op.create_index(op.f('ix_assessment_session_status'), 'assessment_session', ['status'], unique=False)
    op.create_table('assessment_response',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('raw_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('presented_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('media_key', sa.String(length=255), nullable=True),
    sa.Column('asr_transcript', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_item.id'], name=op.f('fk_assessment_response_item_id_assessment_item')),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], name=op.f('fk_assessment_response_session_id_assessment_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_response'))
    )
    op.create_table('result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('proficiency_level', sa.String(length=10), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('skill_scores', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('result_type', sa.Enum('PLACEMENT', 'SPEAKING', 'WRITING', name='resulttype'), nullable=False),
    sa.Column('information_metric', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_session.id'], name=op.f('fk_result_session_id_assessment_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result'))
    )
    op.create_table('placement_result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('average_response_time', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_placement_result_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_result'))
    )
    op.create_table('recommended_item',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('content_id', sa.CHAR(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('target_skill', sa.String(length=50), nullable=False),
    sa.Column('skill_gap_size', sa.DECIMAL(), nullable=True),
    sa.Column('rationale', sa.String(length=500), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', name='recommendationsource'), nullable=False),
    sa.Column('overridden_by', sa.String(length=50), nullable=True),
    sa.Column('overridden_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_recommended_item_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommended_item'))
    )
    op.create_table('speaking_result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('criteria_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_speaking_result_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_result'))
    )
    op.create_table('writing_result',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('essay_text', sa.Text(), nullable=True),
    sa.Column('criteria_scores', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('essay_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], name=op.f('fk_writing_result_result_id_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_result'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writing_result')
    op.drop_table('speaking_result')
    op.drop_table('recommended_item')
    op.drop_table('placement_result')
    op.drop_table('result')
    op.drop_table('assessment_response')
    op.drop_index(op.f('ix_assessment_session_status'), table_name='assessment_session')
    op.drop_table('assessment_session')
    op.drop_table('template_item')
    op.drop_table('lesson')
    op.drop_index(op.f('ix_assigned_assessment_test_taker_id'), table_name='assigned_assessment')
    op.drop_index(op.f('ix_assigned_assessment_status'), table_name='assigned_assessment')
    op.drop_table('assigned_assessment')
    op.drop_table('assessment_config')
    op.drop_table('course')
    op.drop_table('assessment_template')
    op.drop_table('learning_pathway')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('assessment_item')
    # ### end Alembic commands ###
